= Spartakiade 2021 Session Effective Python

Spartakiade 2021 Session Effective Python

For standards and conventions used in this repository, please refer to the section at the end of this README.

NOTE: You can always find the latest release of this container image at in the https://hub.docker.com/r/refnode/spartakiade[dockerhub].

NOTE: Automatic Security and Patch Management for this repository is handled by https://github.com/renovatebot/renovate[renovate].

== Getting started

To be written ...

== Build / Extend / Customize

.Shell commands for cloning the repository
[source,shell]
----
# optional create a git namespace dir and cd into it
mkdir -p $HOME/src/github.com/refnode
cd $HOME/src/github.com/refnode

# clone the repo
git clone git@github.com:refnode/spartakiade-2021-session-effective-python.git
cd spartakiade-2021-session-effective-python
----

After cloning the repo you should execute the bootstrap script in
the repo root directory. The script will

* copy a templated .env for a local 12-factor apps style development
* enable a commit message template
* enable pre-commit.com check for git pre-commit hook
* enable pre-commit.com check for git commit-msg hook

.Shell commands for preparing the repo use and development
[source,shell]
----
# execute the bootstrap script
/bin/sh tools/bootstrap.sh
----

== Standards / Conventions / Resources

The repository uses/follows the following standards/conventions:

* Git Basic Standards (ignore / attributes)
* https://www.conventionalcommits.org/en/v1.0.0/[(Git) Conventional Commits]
* https://pre-commit.com/[Git Pre-Commit Checks]
* https://editorconfig.org[Editor Configuration]
* https://direnv.net/[direnv - Directory based settings management]
* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Format]
