#!/bin/sh

CONTAINER_IMAGE="spartakiade:local"
CONTAINER_NAME="${CONTAINER_NAME:-spartakiade}"
ENV_FILE="$(pwd)/.env"

docker run -ti --rm \
  --name="${CONTAINER_NAME}" \
  --env-file "${ENV_FILE}" \
  "${CONTAINER_IMAGE}" \
  $*
